backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "artwork"
    label: "Artwork"
    description: "Upload all your work here that you'd like to display in the archive.  For 'featured' works on the home page, please set true or false for 'Featured Image'."
    folder: "content/artwork"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Featured Image", name: "featuredimage", widget: "boolean" }
      - {
          label: "Order of Featured Image",
          name: "orderoffeaturedimage",
          widget: "number",
          required: false,
        }
        ##############################
        # JUST GOTTA FIX UP THE OBJECT CONFIGURATION
        ##############################
      - {
          label: "Featured Image Test Object",
          name: "featuredimageobject",
          widget: "object",
          fields:
            [
              {
                label: "Featured Image",
                name: "isfeaturedimage",
                widget: "boolean",
              },
              {
                label: "Order of Featured Image",
                name: "orderofthefeaturedimage",
                widget: "number",
              },
            ],
        }
