backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: src/images/uploads
public_folder: /images/uploads

collections:
  - name: "archivedartwork"
    label: "Archived Artwork"
    description: "Upload all your work here that you'd like to display in the archive."
    folder: "content/archived-artwork"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date Produced",
          name: "date",
          widget: "datetime",
          time_format: false,
        }
      - { label: "Medium", name: "medium", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }

  - name: "featuredArtwork"
    label: "Featured Artwork"
    description: "Upload all your work that you want to feature on the landing page.  Please input the order to set image positions."
    folder: "content/featured-artwork"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Order", name: "order", widget: "number" }

  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "about/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Bio", name: "bio", widget: "string" }

  - label: "Archive"
    name: "archive"
    files:
      - label: "Archive"
        name: "archive"
        file: "content/archive/archive.md"
        fields:
          - name: archive artwork
            label: Archive Artwork
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: string }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  allow_multiple: false,
                }

  - label: "CV"
    name: "cv"
    files:
      - label: "CV"
        name: "cv"
        file: "content/cv/index.md"
        fields:
          - name: education
            label: Education
            widget: list
            fields:
              - { label: School, name: school, widget: string }
              - { label: Qualification, name: qualification, widget: string }
              - { label: Date, name: date, widget: string }
          - name: soloexhibitions
            label: Solo Exhibitions
            widget: list
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Space, name: space, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Date, name: date, widget: string }
          - name: groupexhibitions
            label: Group Exhibitions
            widget: list
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Space, name: space, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Date, name: date, widget: string }
          - name: prizes
            label: Prizes
            widget: list
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Date, name: date, widget: string }
          - name: publications
            label: Publications
            widget: list
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Date, name: date, widget: string }
