backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "archivedartwork"
    label: "Archived Artwork"
    description: "Upload all your work here that you'd like to display in the archive."
    folder: "content/archived-artwork"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date Produced",
          name: "date",
          widget: "datetime",
          time_format: false,
        }
      - { label: "Medium", name: "medium", widget: "string" }
      - { label: "Size", name: "size", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }

  - name: "featuredArtwork"
    label: "Featured Artwork"
    description: "Upload all your work that you want to feature on the landing page.  Please input the order to set image positions."
    folder: "content/featured-artwork"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          allow_multiple: false,
        }
      - { label: "Order", name: "order", widget: "number" }

  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "about/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Bio", name: "bio", widget: "string" }

  - label: "Pages"
    name: "pages"
    files:
      - label: "CV Page"
        name: "cv"
        file: "content/about/about.yml"
        fields:
          - name: education
          label: Education
          widget: list
          fields:
            - { label: School, name: school, widget: string }
            - { label: Qualification, name: qualification, widget: string }
            - { label: Date, name: date, widget: string }
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }

  # - name: "education"
  #   label: "Education"
  #   folder: "content/cv/education"
  #   create: true
  #   slug: "index"
  #   media_folder: ""
  #   public_folder: ""
  #   path: "index"
  #   summary: "Education List"
  #   fields:
  #     - name: education
  #       label: Education
  #       widget: list
  #       fields:
  #         - { label: School, name: school, widget: string }
  #         - { label: Qualification, name: qualification, widget: string }
  #         - { label: Date, name: date, widget: string }

  # - name: "exhibitions"
  #   label: "Exhibitions"
  #   folder: "content/cv/exhibitions"
  #   create: true
  #   slug: "index"
  #   media_folder: ""
  #   public_folder: ""
  #   path: "index"
  #   summary: "Exhibition List"
  #   fields:
  #     - name: exhibitions
  #       label: Exhibitions
  #       widget: list
  #       fields:
  #         - { label: Title, name: title, widget: text }
  #         - { label: Location, name: location, widget: string }
  #         - { label: Date, name: date, widget: string }

  # - name: "prizes"
  #   label: "Prizes"
  #   folder: "content/cv/prizes"
  #   create: true
  #   slug: "index"
  #   media_folder: ""
  #   public_folder: ""
  #   path: "index"
  #   summary: "Prizes List"
  #   fields:
  #     - name: prizes
  #       label: Prizes
  #       widget: list
  #       fields:
  #         - { label: Title, name: title, widget: text }
  #         - { label: Date, name: date, widget: string }

  # - name: "publications"
  #   label: "Publications"
  #   folder: "content/cv/publications"
  #   create: true
  #   slug: "index"
  #   media_folder: ""
  #   public_folder: ""
  #   path: "index"
  #   summary: "Publications List"
  #   fields:
  #     - name: publications
  #       label: Publications
  #       widget: list
  #       fields:
  #         - { label: Title, name: title, widget: text }
  #         - { label: Date, name: date, widget: string }
